export enum LOADER_STATUS {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
}

export enum REQUEST_STATUS {
  LOADING = 'LOADING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
}

export enum ROUTES {
  LOGIN = '/',
  REGISTRATION = '/registration',
  ANALYTICS = '/analytics',
  NOT_FOUND = '*',
}

export enum PAGE_LABEL {
  LOGIN_PAGE = 'LOGIN_PAGE',
  REGISTRATION_PAGE = 'REGISTRATION_PAGE',
  ANALYTICS_PAGE = 'ANALYTICS_PAGE',
  NOT_FOUND_PAGE = 'NOT_FOUND_PAGE',
}
